import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { FormEvent, useContext, useEffect } from 'react';
import { useRouter } from 'next/router';
import { UserContext } from '../context/user';
import axios from 'axios';

interface HomeProps {
  rooms: string[];
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await axios.get('http://localhost:4000/rooms');
  const rooms = res.data;

  if (!rooms) {
    return {
      notFound: true,
    };
  }

  return {
    props: { rooms },
  };
};

const Home: NextPage<HomeProps> = ({ rooms }) => {
  const router = useRouter();
  const { state, setUsername, setRoom } = useContext(UserContext);

  useEffect(() => {
    setRoom('General');
  }, []);

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    console.log(state.room);
    router.push(`/chatroom`);
  };

  const handleChange = (value: string) => {
    setUsername(value);
  };

  return (
    <div className='h-100v flex items-center justify-center'>
      <Head>
        <title>ChatRoom</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-96 shadow-2xl shadow-gray-600 rounded-3xl bg-slate-500 text-white items-center'>
        <h1 className='py-8 text-2xl text-center font-bold'>Chatroom</h1>
        <form className='w-1/2 mx-auto' onSubmit={(e) => handleSubmit(e)}>
          <div>
            <label className='block' htmlFor='username'>
              Username
            </label>
            <input
              className='w-full h-6 text-black placeholder:px-1'
              type='text'
              onChange={(e) => handleChange(e.target.value)}
              name='username'
              id='username'
              placeholder='Enter username...'
              required
            />
          </div>

          <div>
            <label className='block mt-2' htmlFor='room'>
              Room
            </label>
            <select
              className='w-full h-6 text-black'
              name='room'
              id='room'
              onChange={(e) => setRoom(e.target.value)}
            >
              {rooms.map((room, roomId) => {
                return (
                  <option value={room} key={roomId}>
                    {room}
                  </option>
                );
              })}
            </select>
          </div>

          <button
            className='w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 my-8 rounded'
            type='submit'
          >
            Join
          </button>
        </form>
      </div>
    </div>
  );
};

export default Home;
