import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { FormEvent, useContext, useEffect } from 'react';
import { useRouter } from 'next/router';
import { UserContext } from '../context/user';
import axios from 'axios';

interface HomeProps {
  rooms: string[];
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await axios.get('http://localhost:4000/rooms');
  const rooms = res.data;

  if (!rooms) {
    return {
      notFound: true,
    };
  }

  return {
    props: { rooms },
  };
};

const Home: NextPage<HomeProps> = ({ rooms }) => {
  const router = useRouter();
  const { setUsername, setRoom } = useContext(UserContext);

  useEffect(() => {
    setRoom('General');
  });

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    router.push(`/chatroom`);
  };

  const handleChange = (value: string) => {
    setUsername(value);
  };

  return (
    <div>
      <Head>
        <title>ChatRoom</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <form onSubmit={(e) => handleSubmit(e)}>
          <div>
            <label htmlFor='username'>Username</label>
            <input
              type='text'
              onChange={(e) => handleChange(e.target.value)}
              name='username'
              id='username'
              placeholder='Enter username...'
              required
            />
          </div>
          <div>
            <label htmlFor='room'>Room</label>
            <select
              name='room'
              id='room'
              onChange={(e) => setRoom(e.target.value)}
            >
              {rooms.map((room, roomId) => {
                return (
                  <option value={room} key={roomId}>
                    {room}
                  </option>
                );
              })}
              {/* <option value='General'>General</option>
              <option value='JavaScript'>JavaScript</option>
              <option value='Python'>Python</option>
              <option value='PHP'>PHP</option>
              <option value='C#'>C#</option>
              <option value='Ruby'>Ruby</option>
              <option value='Java'>Java</option> */}
            </select>
          </div>
          <button type='submit'>Join</button>
        </form>
      </div>
    </div>
  );
};

export default Home;
